### ISSUE TITLE
debug page : "Validator file is missing"

### ISSUE THREAD

**Issue by guiann** [indexexchange/ix-library-adapters#177]
## Description
After pulling master code,  running npm install  and npm run debug  the console is showing the following error:

"validator file is missing and is required"

At first I though I had forgotten a file in our own adapter but we get the same result in master branch. 

### Steps to Reproduce
- Step 1: pull master branch
- Step 2: npm install
- Step 3: npm run debug
- Step 4: visit : public/debugger/adapter-debugger.html

#### Expected Results
We should be able to test our adapter code

#### Actual Results
Error in console: "validator file is missing and is required"
the page takes several long minutes to load and shows a 404 error on **validator.js** with this error in console:
 "Cannot read property validator of undefined."

**Comment by jas-singh** [comment]
hey @guiann 

can we confirm if the npm run debug was ran while the current working directory was an adapter module for e.g to run the debugger for let's say the adapter optimera you would need to `cd optimera` before executing npm run debug

**Comment by guiann** [comment]
Oh I see, 
I was indeed runing it from the root directory. Missing the last part of this sentence from the README file:
Make sure all your test cases are passing by running npm run debug on OSX or Linux, or npm run win-debug on Windows **in your adapter folder** and then accessing the system tests page.

Thanks for the help.
